# Generated by Django 4.1.1 on 2022-09-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_id', models.CharField(max_length=100)),
                ('Book_name', models.CharField(max_length=100)),
                ('Aisle_number', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
