# Generated by Django 4.1.1 on 2022-09-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='Aisle_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='books',
            name='Book_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='books',
            name='Book_name',
            field=models.CharField(max_length=80),
        ),
    ]
