# Generated by Django 4.1.1 on 2022-09-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_books_aisle_number_alter_books_book_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='id',
        ),
        migrations.AlterField(
            model_name='books',
            name='Book_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
